const portfolioProjects = [
  {
    id: "ai-merchant-assistant",
    title: "AI商家小帮手",
    titleEn: "AI Merchant Assistant",
    type: "AI产品 / 餐饮商家运营",
    typeEn: "AI Product / Merchant Operations",
    platform: "美团餐饮系统 / 移动端 / AI智能体",
    platformEn: "Meituan Food Service / Mobile / AI Agent",
    summary: "围绕餐饮商家多平台运营、经营分析、评价管理和门店互动，设计 AI 商家运营助手体验。",
    summaryEn:
      "An AI merchant assistant experience for restaurant operations, analytics, review management, and store engagement.",
    tags: ["AI商家运营", "餐饮商家", "AI智能体", "移动端"],
    tagsEn: ["AI Operations", "Restaurant Merchant", "AI Agent", "Mobile"],
    facts: [
      ["18", "作品图片"],
      ["AI", "项目方向"],
      ["移动端", "平台范围"],
    ],
    factsEn: [
      ["18", "Portfolio Images"],
      ["AI", "Project Direction"],
      ["Mobile", "Platform Scope"],
    ],
    detailPoints: ["多平台运营", "会员运营", "门店管理", "经营分析"],
    detailPointsEn: ["Multi-platform operations", "Member operations", "Store management", "Business analytics"],
    imageDir: "assets/projects/ai-merchant-assistant",
    imageCount: 18,
    projectBackground: "餐饮商家面临多平台运营、经营分析、评价管理等复杂需求，需要智能化工具提升运营效率。",
    projectBackgroundEn: "Restaurant merchants face complex needs in multi-platform operations, business analytics, and review management, requiring intelligent tools to improve operational efficiency.",
    coreChallenge: "如何将AI能力与商家日常运营场景深度融合，提供自然、高效的交互体验。",
    coreChallengeEn: "How to deeply integrate AI capabilities with merchants' daily operational scenarios to provide natural and efficient interaction experiences.",
    resultMetrics: "商家运营效率提升30%，AI功能使用率达60%，用户满意度提升25%。",
    resultMetricsEn: "Merchant operational efficiency improved 30%, AI feature usage rate reached 60%, user satisfaction increased 25%.",
    methodAssets: "建立AI智能体交互模式、多轮对话设计规范、行业知识图谱和智能推荐算法。",
    methodAssetsEn: "Established AI agent interaction patterns, multi-turn dialogue design guidelines, industry knowledge graphs, and intelligent recommendation algorithms.",
  },
  {
    id: "mini-program-template-library",
    title: "小程序模板库设计",
    titleEn: "Mini Program Template Library",
    type: "餐饮SaaS / C端小程序",
    typeEn: "Food Service SaaS / Consumer Mini Program",
    platform: "美团餐饮系统 / 小程序 / 模板库",
    platformEn: "Meituan Food Service / Mini Program / Template Library",
    summary: "为餐饮商家提供多风格小程序模板，覆盖菜单展示、门店氛围、外卖点餐和品牌表达。",
    summaryEn:
      "A mini program template library for restaurant merchants, covering menus, brand atmosphere, delivery, and ordering flows.",
    tags: ["C端小程序", "模板库", "餐饮SaaS", "视觉体系"],
    tagsEn: ["Consumer Mini Program", "Template Library", "Food SaaS", "Visual System"],
    facts: [
      ["22", "作品图片"],
      ["C端", "用户场景"],
      ["模板库", "项目类型"],
    ],
    factsEn: [
      ["22", "Portfolio Images"],
      ["Consumer", "User Scenario"],
      ["Template", "Project Type"],
    ],
    detailPoints: ["模板风格", "餐饮门店", "小程序点餐", "视觉定制"],
    detailPointsEn: ["Template styles", "Restaurant stores", "Mini program ordering", "Visual customization"],
    imageDir: "assets/projects/mini-program-template-library",
    imageCount: 22,
    projectBackground: "餐饮商家需要快速搭建品牌小程序，但缺乏设计能力和技术资源，需要模板化解决方案。",
    projectBackgroundEn: "Restaurant merchants need to quickly build brand mini programs but lack design capabilities and technical resources, requiring templated solutions.",
    coreChallenge: "如何提供多样化模板风格，同时保证开发效率和品牌差异化表达。",
    coreChallengeEn: "How to provide diverse template styles while ensuring development efficiency and brand differentiation.",
    resultMetrics: "模板覆盖80%餐饮业态，商家搭建时间从7天缩短到1天，模板复用率达90%。抽象出通用经营场景，建立行业模板和组件化能力，从而兼顾个性化体验和规模化交付效率。",
    resultMetricsEn: "Templates cover 80% of restaurant formats, merchant setup time reduced from 7 days to 1 day, template reuse rate reached 90%.",
    methodAssets: "建立模板设计规范、组件库体系、视觉风格系统和快速配置工具。帮助业务提升商户使用效率、降低配置成本，并推动模板化AIGC设计能力复用。",
    methodAssetsEn: "Established template design guidelines, component library system, visual style system, and quick configuration tools.",
  },
  {
    id: "ai-ordering",
    title: "AI智能点餐",
    titleEn: "AI Ordering Experience",
    type: "AI产品 / 餐饮SaaS",
    typeEn: "AI Product / Food Service SaaS",
    platform: "美团餐饮系统 / AI点餐 / 移动端",
    platformEn: "Meituan Food Service / AI Ordering / Mobile",
    summary: "以设计驱动业务价值为目标，探索 AI 在点餐推荐、菜单理解和餐饮服务中的体验表达。",
    summaryEn:
      "An AI ordering experience exploring menu understanding, recommendation, and food service scenarios through product design.",
    tags: ["AI点餐", "餐饮SaaS", "业务价值导向", "移动体验"],
    tagsEn: ["AI Ordering", "Food SaaS", "Business Value", "Mobile UX"],
    facts: [
      ["23", "作品图片"],
      ["AI", "项目方向"],
      ["点餐", "核心场景"],
    ],
    factsEn: [
      ["23", "Portfolio Images"],
      ["AI", "Project Direction"],
      ["Ordering", "Core Scenario"],
    ],
    detailPoints: ["AI推荐", "点餐链路", "菜单理解", "餐饮服务"],
    detailPointsEn: ["AI recommendation", "Ordering journey", "Menu understanding", "Food service"],
    imageDir: "assets/projects/ai-ordering",
    imageCount: 23,
    projectBackground: "传统点餐体验效率低，用户决策成本高，需要AI技术提升点餐效率和个性化体验。",
    projectBackgroundEn: "Traditional ordering experiences are inefficient with high user decision costs, requiring AI technology to improve ordering efficiency and personalized experiences.",
    coreChallenge: "如何平衡AI推荐的精准性与用户自主选择的自由度，避免过度推荐影响体验。",
    coreChallengeEn: "How to balance AI recommendation accuracy with user freedom of choice, avoiding excessive recommendations that impact experience.",
    resultMetrics: "点餐时长缩短40%，客单价提升15%，用户满意度提升20%。",
    resultMetricsEn: "Ordering time reduced 40%, average order value increased 15%, user satisfaction improved 20%.",
    methodAssets: "建立AI推荐算法、菜单语义理解、用户偏好模型和个性化点餐流程。",
    methodAssetsEn: "Established AI recommendation algorithms, menu semantic understanding, user preference models, and personalized ordering flows.",
  },
  {
    id: "peppr-grow",
    title: "PEPPR GROW Product Design",
    titleEn: "PEPPR GROW Product Design",
    type: "海外SaaS / 产品设计",
    typeEn: "Global SaaS / Product Design",
    platform: "C端 + B端 + 官网 + 设计体系",
    platformEn: "Consumer + Business + Website + Design System",
    summary: "围绕海外餐饮品牌的增长产品，覆盖 C端体验、B端能力、官网呈现和设计体系。",
    summaryEn:
      "A global restaurant growth product covering consumer UX, business tools, marketing website, and design system.",
    tags: ["海外SaaS", "Product Design", "C端+B端", "设计体系"],
    tagsEn: ["Global SaaS", "Product Design", "Consumer + Business", "Design System"],
    facts: [
      ["28", "作品图片"],
      ["4类", "平台范围"],
      ["海外", "项目语境"],
    ],
    factsEn: [
      ["28", "Portfolio Images"],
      ["4", "Platform Areas"],
      ["Global", "Project Context"],
    ],
    detailPoints: ["C端体验", "B端工具", "官网", "设计系统"],
    detailPointsEn: ["Consumer UX", "Business tools", "Website", "Design system"],
    imageDir: "assets/projects/peppr-grow",
    imageCount: 28,
    projectBackground: "海外餐饮市场需要统一的增长平台，整合C端体验、B端工具和营销官网。",
    projectBackgroundEn: "Global restaurant market needs a unified growth platform integrating consumer UX, business tools, and marketing website.",
    coreChallenge: "如何设计一套国际化产品体系，满足不同地区、不同规模商家的差异化需求。",
    coreChallengeEn: "How to design an international product system to meet the differentiated needs of merchants in different regions and scales.",
    resultMetrics: "覆盖海外北美市场，用户增长200%，客户续费率提升30%。",
    resultMetricsEn: "Covers North American markets, user growth 200%, customer retention rate improved 30%.",
    methodAssets: "建立国际化设计体系、多语言适配框架、跨地区体验规范和全球设计协作流程。",
    methodAssetsEn: "Established international design system, multilingual adaptation framework, cross-regional experience guidelines, and global design collaboration processes.",
  },
  {
    id: "lemon-right",
    title: "柠檬向右",
    titleEn: "Lemon Right",
    type: "大客定制化 / 小程序体验",
    typeEn: "Key Account Customization / Mini Program UX",
    platform: "会员活动 / 积分商城 / 点餐服务",
    platformEn: "Member Campaign / Points Store / Ordering Service",
    summary: "为柠檬向右品牌打造小程序定制体验，覆盖会员活动、积分商城、点餐与用户服务模块。",
    summaryEn:
      "A custom mini program experience for Lemon Right, covering member campaigns, points store, ordering, and service modules.",
    tags: ["大客定制", "会员活动", "积分商城", "小程序"],
    tagsEn: ["Key Account", "Member Campaign", "Points Store", "Mini Program"],
    facts: [
      ["12", "作品图片"],
      ["小程序", "平台范围"],
      ["定制化", "项目类型"],
    ],
    factsEn: [
      ["12", "Portfolio Images"],
      ["Mini Program", "Platform Scope"],
      ["Custom", "Project Type"],
    ],
    detailPoints: ["会员成长", "积分商城", "门店自取", "外卖点单"],
    detailPointsEn: ["Member growth", "Points store", "Store pickup", "Delivery ordering"],
    imageDir: "assets/projects/lemon-right",
    imageCount: 12,
    projectBackground: "柠檬向右作为新兴茶饮品牌，需要定制化小程序提升会员粘性和订单转化率。",
    projectBackgroundEn: "As an emerging tea brand, Lemon Right needs a customized mini program to improve member engagement and order conversion.",
    coreChallenge: "如何在保持品牌调性的同时，提供流畅的用户体验和高效的运营工具。",
    coreChallengeEn: "How to maintain brand identity while providing smooth user experience and efficient operational tools.",
    resultMetrics: "会员注册量增长150%，订单转化率提升25%，用户留存率提升30%。",
    resultMetricsEn: "Member registration increased 150%, order conversion rate improved 25%, user retention rate increased 30%.",
    methodAssets: "建立品牌视觉系统、会员运营体系、积分商城机制和定制化开发框架。重构点餐链路、会员营销、商家经营工具",
    methodAssetsEn: "Established brand visual system, member operation system, points mall mechanism, and customized development framework.",
  },
  {
    id: "ai-review-expert",
    title: "AI评价专家",
    titleEn: "AI Review Expert",
    type: "AI产品 / 评价管理",
    typeEn: "AI Product / Review Management",
    platform: "美团评价专家 / AI回复 / AI申诉",
    platformEn: "Meituan Review Expert / AI Reply / AI Appeal",
    summary: "从 0 到 1 建设评价管理智能化体验，覆盖评价速览、AI回复、实时差评和差评申诉方案。",
    summaryEn:
      "A from-zero-to-one AI review management experience covering review overview, AI reply, negative review alerts, and appeal workflows.",
    tags: ["AI评价", "AI回复", "实时差评", "AI申诉"],
    tagsEn: ["AI Reviews", "AI Reply", "Negative Review Alerts", "AI Appeal"],
    facts: [
      ["15", "作品图片"],
      ["AI", "项目方向"],
      ["评价", "核心场景"],
    ],
    factsEn: [
      ["15", "Portfolio Images"],
      ["AI", "Project Direction"],
      ["Reviews", "Core Scenario"],
    ],
    detailPoints: ["评价速览", "AI回复", "实时差评", "差评申诉"],
    detailPointsEn: ["Review overview", "AI reply", "Negative review alerts", "Review appeal"],
    imageDir: "assets/projects/ai-review-expert",
    imageCount: 15,
    projectBackground: "商家面对海量评价无法及时响应，差评处理效率低，需要AI辅助提升评价管理能力。",
    projectBackgroundEn: "Merchants face massive reviews and cannot respond in a timely manner, with low efficiency in handling negative reviews, requiring AI assistance to improve review management capabilities.",
    coreChallenge: "如何让AI回复既保持专业性又不失人情味，同时确保回复质量可控。",
    coreChallengeEn: "How to make AI replies both professional and empathetic while ensuring reply quality is controllable.",
    resultMetrics: "差评响应时间缩短80%，AI评价使用率80%，商家满意度提升35%。",
    resultMetricsEn: "Negative review response time reduced 80%, AI review usage rate improved 80%, merchant satisfaction increased 35%.",
    methodAssets: "建立AI回复模型、差评识别算法、情感分析引擎和申诉流程规范。",
    methodAssetsEn: "Established AI reply models, negative review identification algorithms, sentiment analysis engines, and appeal process guidelines.",
  },
  {
    id: "b2b-design-system",
    title: "B端设计体系",
    titleEn: "B2B Design System",
    type: "B端设计体系 / 企业级产品",
    typeEn: "B2B Design System / Enterprise Product",
    platform: "企业级B端产品 / 组件规范 / 复杂系统",
    platformEn: "Enterprise B2B Product / Component Guidelines / Complex Systems",
    summary: "围绕企业级 B端产品沉淀设计体系，覆盖组件规范、复杂系统体验和规模化协作方法。",
    summaryEn:
      "An enterprise B2B design system covering component guidelines, complex product UX, and scalable collaboration methods.",
    tags: ["B端设计体系", "组件规范", "复杂系统", "规模化协作"],
    tagsEn: ["B2B Design System", "Component Guidelines", "Complex Systems", "Scalable Collaboration"],
    facts: [
      ["8", "作品图片"],
      ["B端", "项目方向"],
      ["体系化", "项目类型"],
    ],
    factsEn: [
      ["8", "Portfolio Images"],
      ["B2B", "Project Direction"],
      ["Systematic", "Project Type"],
    ],
    detailPoints: ["组件规范", "复杂系统", "体验一致性", "规模化协作"],
    detailPointsEn: ["Component guidelines", "Complex systems", "Experience consistency", "Scaled collaboration"],
    imageDir: "assets/projects/b2b-design-system",
    imageCount: 8,
    projectBackground: "企业级B端产品复杂度高，团队协作效率低，需要建立统一的设计体系提升协作效率和体验一致性。",
    projectBackgroundEn: "Enterprise B2B products are highly complex with low team collaboration efficiency, requiring a unified design system to improve collaboration efficiency and experience consistency.",
    coreChallenge: "如何在满足复杂业务需求的同时，保持设计体系的灵活性和可扩展性。",
    coreChallengeEn: "How to maintain design system flexibility and scalability while meeting complex business requirements.",
    resultMetrics: "设计效率提升60%，组件复用率达80%，跨团队协作成本降低50%。",
    resultMetricsEn: "Design efficiency improved 60%, component reuse rate reached 80%, cross-team collaboration costs reduced 50%.",
    methodAssets: "建立企业级组件库、设计规范文档、设计工具插件和协作流程体系。",
    methodAssetsEn: "Established enterprise component library, design specification documents, design tool plugins, and collaboration process system.",
  },
  {
    id: "international-design",
    title: "国际化设计",
    titleEn: "International Design",
    type: "国际化设计 / 海外业务",
    typeEn: "International Design / Global Business",
    platform: "海外业务 / 多语言本地化 / 多地区体验",
    platformEn: "Global Business / Multilingual Localization / Regional Experience",
    summary: "围绕海外业务和多地区产品体验，国际化设计策略、多语言本地化和跨文化体验适配。",
    summaryEn:
      "International design strategy, multilingual localization, and cross-cultural experience adaptation for global business and regional product experiences.",
    tags: ["国际化设计", "海外业务", "本地化", "多地区体验"],
    tagsEn: ["International Design", "Global Business", "Localization", "Regional UX"],
    facts: [
      ["13", "作品图片"],
      ["海外", "项目语境"],
      ["国际化", "项目方向"],
    ],
    factsEn: [
      ["13", "Portfolio Images"],
      ["Global", "Project Context"],
      ["International", "Project Direction"],
    ],
    detailPoints: ["海外业务", "多语言本地化", "跨文化体验", "国际化策略"],
    detailPointsEn: ["Global business", "Multilingual localization", "Cross-cultural UX", "International strategy"],
    imageDir: "assets/projects/international-design",
    imageCount: 13,
    projectBackground: "业务拓展至海外市场，需要解决多语言、多文化、多地区的产品体验适配问题。",
    projectBackgroundEn: "Business expanded to overseas markets, requiring solutions for multilingual, multicultural, and multi-regional product experience adaptation.",
    coreChallenge: "如何在保持产品一致性的同时，满足不同地区用户的文化习惯和使用偏好。",
    coreChallengeEn: "How to maintain product consistency while meeting cultural habits and usage preferences of users in different regions.",
    resultMetrics: "成功进入15+海外市场，本地化适配周期缩短60%，用户满意度提升25%。",
    resultMetricsEn: "Successfully entered 15+ overseas markets, localization cycle reduced 60%, user satisfaction improved 25%.",
    methodAssets: "建立国际化设计规范、多语言适配框架、文化适配指南和本地化流程体系。",
    methodAssetsEn: "Established international design guidelines, multilingual adaptation framework, cultural adaptation guides, and localization process system.",
  },
  {
    id: "customer-experience-management",
    title: "客户体验管理",
    titleEn: "Customer Experience Management",
    type: "客户体验管理 / 体验度量",
    typeEn: "Customer Experience Management / Experience Metrics",
    platform: "CSAT / NPS / 工单 / 续签体验",
    platformEn: "CSAT / NPS / Tickets / Renewal Experience",
    summary: "围绕客户体验管理体系，展示从体验问题识别、指标度量到持续优化的设计管理方法。",
    summaryEn:
      "A customer experience management system covering experience issue identification, metric tracking, and continuous optimization methods.",
    tags: ["客户体验管理", "CSAT", "NPS", "体验度量"],
    tagsEn: ["CEM", "CSAT", "NPS", "Experience Metrics"],
    facts: [
      ["10", "作品图片"],
      ["CEM", "项目方向"],
      ["度量", "核心方法"],
    ],
    factsEn: [
      ["10", "Portfolio Images"],
      ["CEM", "Project Direction"],
      ["Metrics", "Core Method"],
    ],
    detailPoints: ["体验诊断", "指标度量", "工单分析", "持续优化"],
    detailPointsEn: ["Experience diagnosis", "Metric tracking", "Ticket analysis", "Continuous optimization"],
    imageDir: "assets/projects/customer-experience-management",
    imageCount: 10,
    projectBackground: "客户体验数据分散，缺乏统一的度量体系和优化闭环，需要建立系统化的体验管理平台。",
    projectBackgroundEn: "Customer experience data is scattered, lacking a unified measurement system and optimization loop, requiring a systematic experience management platform.",
    coreChallenge: "如何将抽象的体验感受转化为可量化的指标，建立体验与业务结果的关联。",
    coreChallengeEn: "How to translate abstract experience feelings into quantifiable metrics and establish connections between experience and business outcomes.",
    resultMetrics: "CSAT提升15%，NPS提升20分，工单量减少30%，客户续费率提升25%。",
    resultMetricsEn: "CSAT improved 15%, NPS increased 20 points, ticket volume reduced 30%, customer retention rate improved 25%.",
    methodAssets: "建立体验度量体系、客户反馈闭环、数据分析模型和体验优化方法论。",
    methodAssetsEn: "Established experience measurement system, customer feedback loop, data analysis models, and experience optimization methodology.",
  },
  {
    id: "design-management",
    title: "设计管理与领导力",
    titleEn: "Design Management and Leadership",
    type: "设计管理 / 团队运营",
    typeEn: "Design Management / Team Operations",
    platform: "团队管理 / 设计流程 / 评审机制 / 人才培养",
    platformEn: "Team Management / Design Process / Review Mechanism / Talent Growth",
    summary: "设计管理与领导力方法，覆盖业务理解、设计策略、团队管理、设计体系、跨团队影响、复杂项目推动、数据与质效度量和设计价值衡量。",
    summaryEn:
      "Design management and leadership methods covering business understanding, design strategy, team management, design systems, cross-functional influence, complex project delivery, quality metrics, and design value measurement.",
    tags: ["设计管理", "团队运营", "设计评审", "人才培养"],
    tagsEn: ["Design Management", "Team Operations", "Design Review", "Talent Growth"],
    facts: [
      ["12", "作品图片"],
      ["管理", "项目方向"],
      ["团队", "核心场景"],
    ],
    factsEn: [
      ["12", "Portfolio Images"],
      ["Management", "Project Direction"],
      ["Team", "Core Scenario"],
    ],
    detailPoints: ["业务理解", "设计策略", "团队领导力", "设计价值衡量"],
    detailPointsEn: ["Business understanding", "Design strategy", "Team leadership", "Design value measurement"],
    projectBackground: "美团餐饮SaaS业务快速扩张，设计团队从8人增长至20人，需要建立系统化的设计管理机制来支撑多产品线并行开发。",
    projectBackgroundEn: "Meituan Food Service SaaS business expanded rapidly, design team grew from 8 to 20 members, requiring systematic design management to support multiple product lines.",
    coreChallenge: "如何在高压迭代中保持设计质量一致性，同时建立可复制的设计流程和人才培养体系。",
    coreChallengeEn: "How to maintain design quality consistency under high-pressure iterations while building replicable design processes and talent development systems.",
    myRole: "设计经理，负责设计团队管理、设计流程建设、评审机制建立、人才培养和跨团队协作。",
    myRoleEn: "Design Manager, responsible for team management, design process establishment, review mechanisms, talent development, and cross-team collaboration.",
    resultMetrics: "设计产出效率提升2倍，团队成员年度晋升率20%，设计高分质量提升50%，设计资产复用率提升50%。",
    resultMetricsEn: "Design output efficiency doubled, annual promotion rate 20%, high score design quality improved 50%, design asset reuse improved 50%.",
    methodAssets: "建立设计评审机制、需求分级体系、组件治理流程、用户体验管理、AI设计变革和跨职能设计协同机制。",
    methodAssetsEn: "Established design review mechanism, requirement grading system, component governance process, user experience management, AI design transformation, and cross-functional design collaboration mechanism.",
    imageDir: "assets/projects/design-management",
    imageCount: 12,
  },
];
