const portfolioProjects = [
  {
    id: "ai-merchant-assistant",
    title: "AI商家小帮手",
    titleEn: "AI Merchant Assistant",
    type: "AI产品 / 餐饮商家运营",
    typeEn: "AI Product / Merchant Operations",
    platform: "美团餐饮系统 / 移动端 / AI智能体",
    platformEn: "Meituan Food Service / Mobile / AI Agent",
    summary: "围绕餐饮商家多平台运营、经营分析、评价管理和门店互动，设计 AI 商家运营助手体验。",
    summaryEn:
      "An AI merchant assistant experience for restaurant operations, analytics, review management, and store engagement.",
    tags: ["AI商家运营", "餐饮商家", "AI智能体", "移动端"],
    tagsEn: ["AI Operations", "Restaurant Merchant", "AI Agent", "Mobile"],
    facts: [
      ["20", "作品图片"],
      ["AI", "项目方向"],
      ["移动端", "平台范围"],
    ],
    factsEn: [
      ["20", "Portfolio Images"],
      ["AI", "Project Direction"],
      ["Mobile", "Platform Scope"],
    ],
    detailPoints: ["多平台运营", "会员运营", "门店管理", "经营分析"],
    detailPointsEn: ["Multi-platform operations", "Member operations", "Store management", "Business analytics"],
    imageDir: "assets/projects/ai-merchant-assistant",
    imageCount: 20,
  },
  {
    id: "mini-program-template-library",
    title: "小程序模板库设计",
    titleEn: "Mini Program Template Library",
    type: "餐饮SaaS / C端小程序",
    typeEn: "Food Service SaaS / Consumer Mini Program",
    platform: "美团餐饮系统 / 小程序 / 模板库",
    platformEn: "Meituan Food Service / Mini Program / Template Library",
    summary: "为餐饮商家提供多风格小程序模板，覆盖菜单展示、门店氛围、外卖点餐和品牌表达。",
    summaryEn:
      "A mini program template library for restaurant merchants, covering menus, brand atmosphere, delivery, and ordering flows.",
    tags: ["C端小程序", "模板库", "餐饮SaaS", "视觉体系"],
    tagsEn: ["Consumer Mini Program", "Template Library", "Food SaaS", "Visual System"],
    facts: [
      ["25", "作品图片"],
      ["C端", "用户场景"],
      ["模板库", "项目类型"],
    ],
    factsEn: [
      ["25", "Portfolio Images"],
      ["Consumer", "User Scenario"],
      ["Template", "Project Type"],
    ],
    detailPoints: ["模板风格", "餐饮门店", "小程序点餐", "视觉定制"],
    detailPointsEn: ["Template styles", "Restaurant stores", "Mini program ordering", "Visual customization"],
    imageDir: "assets/projects/mini-program-template-library",
    imageCount: 25,
  },
  {
    id: "ai-ordering",
    title: "AI智能点餐",
    titleEn: "AI Ordering Experience",
    type: "AI产品 / 餐饮SaaS",
    typeEn: "AI Product / Food Service SaaS",
    platform: "美团餐饮系统 / AI点餐 / 移动端",
    platformEn: "Meituan Food Service / AI Ordering / Mobile",
    summary: "以设计驱动业务价值为目标，探索 AI 在点餐推荐、菜单理解和餐饮服务中的体验表达。",
    summaryEn:
      "An AI ordering experience exploring menu understanding, recommendation, and food service scenarios through product design.",
    tags: ["AI点餐", "餐饮SaaS", "业务价值导向", "移动体验"],
    tagsEn: ["AI Ordering", "Food SaaS", "Business Value", "Mobile UX"],
    facts: [
      ["39", "作品图片"],
      ["AI", "项目方向"],
      ["点餐", "核心场景"],
    ],
    factsEn: [
      ["39", "Portfolio Images"],
      ["AI", "Project Direction"],
      ["Ordering", "Core Scenario"],
    ],
    detailPoints: ["AI推荐", "点餐链路", "菜单理解", "餐饮服务"],
    detailPointsEn: ["AI recommendation", "Ordering journey", "Menu understanding", "Food service"],
    imageDir: "assets/projects/ai-ordering",
    imageCount: 39,
  },
  {
    id: "peppr-grow",
    title: "PEPPR GROW Product Design",
    titleEn: "PEPPR GROW Product Design",
    type: "海外SaaS / 产品设计",
    typeEn: "Global SaaS / Product Design",
    platform: "C端 + B端 + 官网 + 设计体系",
    platformEn: "Consumer + Business + Website + Design System",
    summary: "围绕海外餐饮品牌的增长产品，覆盖 C端体验、B端能力、官网呈现和设计体系。",
    summaryEn:
      "A global restaurant growth product covering consumer UX, business tools, marketing website, and design system.",
    tags: ["海外SaaS", "Product Design", "C端+B端", "设计体系"],
    tagsEn: ["Global SaaS", "Product Design", "Consumer + Business", "Design System"],
    facts: [
      ["32", "作品图片"],
      ["4类", "平台范围"],
      ["海外", "项目语境"],
    ],
    factsEn: [
      ["32", "Portfolio Images"],
      ["4", "Platform Areas"],
      ["Global", "Project Context"],
    ],
    detailPoints: ["C端体验", "B端工具", "官网", "设计系统"],
    detailPointsEn: ["Consumer UX", "Business tools", "Website", "Design system"],
    imageDir: "assets/projects/peppr-grow",
    imageCount: 32,
  },
  {
    id: "lemon-right",
    title: "柠檬向右",
    titleEn: "Lemon Right",
    type: "大客定制化 / 小程序体验",
    typeEn: "Key Account Customization / Mini Program UX",
    platform: "会员活动 / 积分商城 / 点餐服务",
    platformEn: "Member Campaign / Points Store / Ordering Service",
    summary: "为柠檬向右品牌打造小程序定制体验，覆盖会员活动、积分商城、点餐与用户服务模块。",
    summaryEn:
      "A custom mini program experience for Lemon Right, covering member campaigns, points store, ordering, and service modules.",
    tags: ["大客定制", "会员活动", "积分商城", "小程序"],
    tagsEn: ["Key Account", "Member Campaign", "Points Store", "Mini Program"],
    facts: [
      ["13", "作品图片"],
      ["小程序", "平台范围"],
      ["定制化", "项目类型"],
    ],
    factsEn: [
      ["13", "Portfolio Images"],
      ["Mini Program", "Platform Scope"],
      ["Custom", "Project Type"],
    ],
    detailPoints: ["会员成长", "积分商城", "门店自取", "外卖点单"],
    detailPointsEn: ["Member growth", "Points store", "Store pickup", "Delivery ordering"],
    imageDir: "assets/projects/lemon-right",
    imageCount: 13,
  },
  {
    id: "ai-review-expert",
    title: "AI评价专家",
    titleEn: "AI Review Expert",
    type: "AI产品 / 评价管理",
    typeEn: "AI Product / Review Management",
    platform: "美团评价专家 / AI回复 / AI申诉",
    platformEn: "Meituan Review Expert / AI Reply / AI Appeal",
    summary: "从 0 到 1 建设评价管理智能化体验，覆盖评价速览、AI回复、实时差评和差评申诉方案。",
    summaryEn:
      "A from-zero-to-one AI review management experience covering review overview, AI reply, negative review alerts, and appeal workflows.",
    tags: ["AI评价", "AI回复", "实时差评", "AI申诉"],
    tagsEn: ["AI Reviews", "AI Reply", "Negative Review Alerts", "AI Appeal"],
    facts: [
      ["20", "作品图片"],
      ["AI", "项目方向"],
      ["评价", "核心场景"],
    ],
    factsEn: [
      ["20", "Portfolio Images"],
      ["AI", "Project Direction"],
      ["Reviews", "Core Scenario"],
    ],
    detailPoints: ["评价速览", "AI回复", "实时差评", "差评申诉"],
    detailPointsEn: ["Review overview", "AI reply", "Negative review alerts", "Review appeal"],
    imageDir: "assets/projects/ai-review-expert",
    imageCount: 20,
  },
  {
    id: "b2b-design-system",
    title: "B端设计体系",
    titleEn: "B2B Design System",
    type: "B端设计体系 / 企业级产品",
    typeEn: "B2B Design System / Enterprise Product",
    platform: "企业级B端产品 / 组件规范 / 复杂系统",
    platformEn: "Enterprise B2B Product / Component Guidelines / Complex Systems",
    summary: "围绕企业级 B端产品沉淀设计体系，覆盖组件规范、复杂系统体验和规模化协作方法。",
    summaryEn:
      "An enterprise B2B design system covering component guidelines, complex product UX, and scalable collaboration methods.",
    tags: ["B端设计体系", "组件规范", "复杂系统", "规模化协作"],
    tagsEn: ["B2B Design System", "Component Guidelines", "Complex Systems", "Scalable Collaboration"],
    facts: [
      ["9", "作品图片"],
      ["B端", "项目方向"],
      ["体系化", "项目类型"],
    ],
    factsEn: [
      ["9", "Portfolio Images"],
      ["B2B", "Project Direction"],
      ["Systematic", "Project Type"],
    ],
    detailPoints: ["组件规范", "复杂系统", "体验一致性", "规模化协作"],
    detailPointsEn: ["Component guidelines", "Complex systems", "Experience consistency", "Scaled collaboration"],
    imageDir: "assets/projects/b2b-design-system",
    imageCount: 9,
  },
  {
    id: "international-design",
    title: "国际化设计",
    titleEn: "International Design",
    type: "国际化设计 / 海外业务",
    typeEn: "International Design / Global Business",
    platform: "海外业务 / 多语言本地化 / 多地区体验",
    platformEn: "Global Business / Multilingual Localization / Regional Experience",
    summary: "围绕海外业务和多地区产品体验，国际化设计策略、多语言本地化和跨文化体验适配。",
    summaryEn:
      "International design strategy, multilingual localization, and cross-cultural experience adaptation for global business and regional product experiences.",
    tags: ["国际化设计", "海外业务", "本地化", "多地区体验"],
    tagsEn: ["International Design", "Global Business", "Localization", "Regional UX"],
    facts: [
      ["15", "作品图片"],
      ["海外", "项目语境"],
      ["国际化", "项目方向"],
    ],
    factsEn: [
      ["15", "Portfolio Images"],
      ["Global", "Project Context"],
      ["International", "Project Direction"],
    ],
    detailPoints: ["海外业务", "多语言本地化", "跨文化体验", "国际化策略"],
    detailPointsEn: ["Global business", "Multilingual localization", "Cross-cultural UX", "International strategy"],
    imageDir: "assets/projects/international-design",
    imageCount: 15,
  },
  {
    id: "customer-experience-management",
    title: "客户体验管理",
    titleEn: "Customer Experience Management",
    type: "客户体验管理 / 体验度量",
    typeEn: "Customer Experience Management / Experience Metrics",
    platform: "CSAT / NPS / 工单 / 续签体验",
    platformEn: "CSAT / NPS / Tickets / Renewal Experience",
    summary: "围绕客户体验管理体系，展示从体验问题识别、指标度量到持续优化的设计管理方法。",
    summaryEn:
      "A customer experience management system covering experience issue identification, metric tracking, and continuous optimization methods.",
    tags: ["客户体验管理", "CSAT", "NPS", "体验度量"],
    tagsEn: ["CEM", "CSAT", "NPS", "Experience Metrics"],
    facts: [
      ["12", "作品图片"],
      ["CEM", "项目方向"],
      ["度量", "核心方法"],
    ],
    factsEn: [
      ["12", "Portfolio Images"],
      ["CEM", "Project Direction"],
      ["Metrics", "Core Method"],
    ],
    detailPoints: ["体验诊断", "指标度量", "工单分析", "持续优化"],
    detailPointsEn: ["Experience diagnosis", "Metric tracking", "Ticket analysis", "Continuous optimization"],
    imageDir: "assets/projects/customer-experience-management",
    imageCount: 12,
  },
  {
    id: "design-management",
    title: "设计管理",
    titleEn: "Design Management",
    type: "设计管理 / 团队运营",
    typeEn: "Design Management / Team Operations",
    platform: "团队管理 / 设计流程 / 评审机制 / 人才培养",
    platformEn: "Team Management / Design Process / Review Mechanism / Talent Growth",
    summary: "设计团队管理、评审机制、流程建设、人才培养和设计运营方法，设计综合能力。",
    summaryEn:
      "Design team management, review mechanisms, process building, talent development, and design operations methods.",
    tags: ["设计管理", "团队运营", "设计评审", "人才培养"],
    tagsEn: ["Design Management", "Team Operations", "Design Review", "Talent Growth"],
    facts: [
      ["6", "作品图片"],
      ["管理", "项目方向"],
      ["团队", "核心场景"],
    ],
    factsEn: [
      ["6", "Portfolio Images"],
      ["Management", "Project Direction"],
      ["Team", "Core Scenario"],
    ],
    detailPoints: ["团队管理", "设计流程", "评审机制", "人才培养"],
    detailPointsEn: ["Team leadership", "Design process", "Review mechanism", "Talent development"],
    imageDir: "assets/projects/design-management",
    imageCount: 6,
  },
];
